main: de.raidcraft.rcmultiworld.RCMultiWorldPlugin
name: RCMultiWorld
version: ${project.version}#${BUILDS_ALL_TIME}
description: Provides multiworld support.
author: Strasse36
website: http://www.raid-craft.de
depend: [RaidCraft-API]
database: true
api-version: 1.13