main: de.raidcraft.rcmultiworld.RCMultiWorldPlugin
name: RCMultiWorld
version: ${project.version}#${build.number}
description: Provides multiworld support.
author: Strasse36
website: http://www.raid-craft.de
depend: [RaidCraft-API]